name: Demo pipeline

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches: [main, dev]
    #schedule:
     #  - cron:
jobs:

    setup_job:
        runs-on: ubuntu-latest # macos-latest, windows-latest
        steps:
            - name: checkout repo
              uses: action/checktout@v4
            - name: create file
              run: touch github-action.txt
            - name: print Hello World
              run: echo Hello World
            - name: display readme file
              run: cat README.md

    build_job:
        runs-on: windows-latest
        steps:
            - name: dispaly Hello
              run: echo Hello

    deploy_job:
        runs-on: macos-latest
        steps:
            - run: echo Hello mac
